### PR TITLE
Re-document flycheck-eglot compatibility layer

### PR DESCRIPTION
**Pull request by gagbo**
Since joaotavora/eglot@da7ff4883d3108468265fdc16a217d8e6aff92f2,
the callback defined by `eglot-flymake-backend` is only called when
flymake-mode is active. ~~To circumvent this limitation, we let-bind
`flymake-mode` around `eglot-handle-notification`.~~ Not relevant, see later comment for the actual workaround

Relates to flycheck/flycheck#1592 discussion

### CODE REVIEW

**Comment by gagbo** [comment]
This is not over, there are still situations just after a save where the diagnostics don't seem to bubble up correctly

**Comment by gagbo** [comment]
Copy-pasting the commit:

Since joaotavora/eglot@da7ff48,
the callback defined by `eglot-flymake-backend` is only called when
flymake-mode is active. To circumvent this limitation, we tried to
let-bind `flymake-mode` around `eglot-handle-notification`.

That does not work because eglot-handle-notification uses
with-current-buffer macro in its implementation, and within that macro
the let binding is not used anymore.

It is also impossible to use setq-default in an :around advice, because
the value of flymake-mode in those buffers is not-default and set to
nil. Eglot starts flymake-mode on its entry-point, so
+lsp-prefer-flycheck-h has to set flymake-mode to nil in order to avoid
both implementations showing duplicate bindings.

So instead the code of the publishDiagnostics handler is copied and the
case for flycheck is manually added.

Used https://github.com/joaotavora/eglot/blob/4c85df2b04e467b8ed0eca68bd202fd0e7b671f4/eglot.el#L1586
as base to patch here.

**Comment by gagbo** [comment]
And now I remembered that you cannot merge that because the code is GPLv3 and I did not write it. Moved status back to draft

@joaotavora do you think you'd accept a patch to add a way to trigger an arbitrary callback on `publishDiagnostics`, so that we could keep a "push" architecture (server sends notification to eglot and diagnostics are only updated at that point) with flycheck ?

I would like to avoid polling `eglot--unreported-diagnostics` value if possible, since there is no good single value for a delay.

**Comment by AlexDaniel** [comment]
So what's the status of this? I'm trying to figure out how to make doom emacs work with vue-mode.

**Comment by joaotavora** [comment]
I'm finally able to comment here after being mentioned (I wasn't for a while because of a non-contributor block).   I'll try to see what's up this coming week.  It seems like an API of sorts is being requested from Flymake or Eglot.  I don't understand fully why it is needed (I may have understood it in the past and forgotten it).  And I don't understand why doom emacs users can't just use Flymake, like regular Emacs users. It's ok to prefer something else, but is Flymake somehow blocked in Doom?

**Comment by hlissner** [comment]
> I'm finally able to comment here after being mentioned (I wasn't for a while because of a non-contributor block)

@joaotavora Sorry for the bother! Just a big reorganization effort happening behind the scenes.

> And I don't understand why doom emacs users can't just use Flymake, like regular Emacs users. It's ok to prefer something else, but is Flymake somehow blocked in Doom?

It isn't blocked. Flycheck integration in Doom is simply more polished and I'd like to avoid locking users out of the larger selection of checkers flycheck et plugins offer at the moment.

**Comment by hlissner** [comment]
> I would like to avoid polling eglot--unreported-diagnostics value if possible, since there is no good single value for a delay.

@gagbo Would this work, instead of redefining `eglot-handle-notification`'s primary method?

```elisp
(cl-defmethod eglot-handle-notification
  :after
  (server (_method (eql textDocument/publishDiagnostics)) &key uri diagnostics
          &allow-other-keys)
  (when (and eglot--unreported-diagnostics
             flycheck-mode)
    (flycheck-buffer)))
```

**Comment by joaotavora** [comment]
> It isn't blocked. Flycheck integration in Doom is simply more polished and I'd like to avoid locking users out of the larger selection of checkers flycheck et plugins offer at the moment. I do have better flymake integration planned, but it'll be some time until I get there.

Makes sense.  BtW, completely unrelated to this, the Flymake mode line is now "properly" customizable it should be easier to fit its indicators in a fancy mode-line.  I remember you requesting this in the past.

> @gagbo Would something like this work, instead of redefining eglot-handle-notification's primary method?

@hlissner  it's a nice idea.  It's not 100% safe in itself, because Eglot itself could want to put something there, and there's only one "slot" for doing so, but it's relatively safe and much better than redefining the whole method.  Unfortunately, the larger problem is that you're still using internal variables of the Eglot project.  It's not the first time I see this in Doom, and it's a hazard that has brought problems in the past (once at least in Eglot/Doom specifically, probably millions of times in software dev in general).

Anyway, @gagbo ,I don't see what's the problem of having the Flycheck checker just call `eglot-flymake-backend` which is an external function, and has a well-behaved protocol.  Its first argument is called with the list of diagnostics objects, which also have a well-defined external API.  So why can't you use that?  It _seems_ a better idea than:

* locking `flycheck-buffer` to the to the diagnostic publication (aren't there other checkers be invoked there possible that would find this odd?)
* using internal variables

You may probably _still_ need the `:after` though, which is to _clean_ all Eglot diagnostics when the `textDocument/publishDiagnostics` comes in.  EDIT: never mind, you don't, Eglot will do it for you.  You just have to be careful
to support all the cases of the `REPORT-FN` function as described in `C-h v flymake-diagnostic-functions RET`.

Let me know what you think.

**Comment by gagbo** [comment]
> Anyway, @gagbo ,I don't see what's the problem of having the Flycheck checker just call `eglot-flymake-backend` which is an external function, and has a well-behaved protocol. Its first argument is called with the list of diagnostics objects, which also have a well-defined external API. So why can't you use that? 

The main issue with this is that I wish diagnostics updates to have a "push" architecture instead of a "polling" one.

## Polling
Having the flycheck checker call `eglot-flymake-backend`, and have the hacky `flymake->flycheck` conversion, is fine and would work. But _when_ should flycheck call that ? The diagnostics are updated asynchronously by an external process pushing diagnostics to eglot eventually. So either:

### Running on a timer

You run the `flycheck-checker` on a timer, to poll eglot if it received diagnostics for a flycheck diagnostics updates. I don’t like this because it introduces "lag" between diagnostics and display, and because tweaking the delay value will be the source of a lot of gh issues. (There has been this problem with changing `company-idle-delay` in the past)

### Flycheck API to trigger

You use a flycheck trigger to trigger the update. The issue there is that there’s no trigger at all that can detect the reception of an LSP notification ([only](https://github.com/flycheck/flycheck/blob/01396a5eff9fa494285e0d3139838231c05e3948/flycheck.el#L684) on save, idle _after a change_, idle _after a buffer switch_, on a new line, or when flycheck is active ). 

Quick example: when you open a file in a big Rust project, the LSP server might need 1, 10, or 30 seconds to send the first diagnostics notification; there’s no trigger that can handle that arbitrary delay on file opening (without modifying the buffer) :
- on save doesn’t because you only opened the file
- idle after change doesn’t because you only opened the file
- idle after buffer switch means you’d have to know the exact delay for each project, each file on each computer depending on the current load as well (and use the `max` of the values, or use a dir-locals to customize that delay)
- new line doesn’t work because you only opened the file
- on flycheck activation doesn’t work because the diagnostics are never ready when flycheck is activated

So we would have to use a weird combination of existing ones, and explain users how to bend Emacs to trigger an update. 

### Variable watcher on eglot internal

It doesn’t work because variable watcher would need to also clean up the list of diagnostics, and (for good reasons), a variable watcher cannot change the variable that’s being changed (I tried a when-let with operation equal to `set` but it didn’t really work)

# Pushing
That’s mostly why I’d prefer to keep the same behaviour as before. i.e. when eglot receives the relevant publishDiagnostics notification, it automatically called `eglot-flymake-report-fn` and that’s where we used to place the flycheck "force-update" code that would change diagnostics for the user. Now that it’s gated by `flymake-mode` variable, I just added a flycheck specific case, and it felt "cleaner" at that point to just call `flycheck-buffer` in that case.

The `after` method for generics seems cool, I didn’t know that at all. It would solve my issue I think.

**Comment by joaotavora** [comment]
Right, @gabgo, you are reaching the same discussion I had with myself when first doing this.  I came to the conclusion that polling was better becasue: i

- it's cleaner (less code).  And yes, Eglot was running on a "push" architecture for a while in the beginning.
- it works well with multiple Flymake backends, some of which don't have this external  unpredictable asynchronous thing telling them when to publish.
- There's really no significant effort wasted when you poll and find out there wasn't anything to report
- Some Flymake (or Flycheck, I guess) users might want to only check "on demand".  This is "manual polling".  We shouldn't, in principle, break that for them.

> I didn’t know that at all. It would solve my issue I think.

It's better than what you had before, but you're still abusing Eglot's internals.  I guess I could make a `eglot-unreported-diagnostics` accessor function, if you really do think it would be cleaner with this push architecture.  You can make a PR for that in the Eglot repo if you think this is the way to go.

**Comment by gagbo** [comment]
Pushing allows to reduce latency the most, and most "complaints" regarding Doom and Emacs and general are around perceived responsiveness, so I do think it's a good thing to keep this ability.

With that being said, we aren't forced to forcefully call `(flycheck-buffer)` (or any other contender that might come in the future) each time we receive diagnostics. We could support both on eglot by having

- a `eglot-diagnostics-callback` variable that is a callable that must take at least one argument. If non-nil, Eglot calls this callback with `eglot--unreported-diagnostics` list as first argument, _and resets the diagnostics list after that call_
- an accessor/resetter to the `eglot--unreported-diagnostics` list

This way anyone can write their own callback, if they want to keep eglot pushing and reduce perceived latency; or you can leave the callback to nil and handle the diagnostics list manually by polling the list and resetting it when you're done with it.

(If a "pusher" wants to keep the "unreported-diagnostics" state for whatever reason, they're free to use a local variable to store this in the callback, but I think that eglot resetting the list after having called the callback is cleaner)

**Comment by joaotavora** [comment]
> Pushing allows to reduce latency the most, and most "complaints" regarding Doom and Emacs and general are around perceived responsiveness, so I do think it's a good thing to keep this ability.

Note that latency will always be a function of `eglot-send-changes-idle-time` anyway.  So your strategy is only potentially useful to deduce the difference between that value and `flymake-no-changes-timeout`, which, by default, is... 0!  (they are both 0.5 seconds).  And they are _both_ configurable.

This means that as soon as the changes are published Eglot --> Server, flymake _also_ kicks in and puts the correct callback in place, ready to get called as soon as possible.  When the diagnostics come in, it _is_ called.

So unless there's a bug in the current `eglot.el` (always possible), I don't see how your `push` scheme can gain any responsiveness.

>  a eglot-diagnostics-callback variable that is a callable that must take at least one argument. If non-nil, Eglot calls this callback 
> with eglot--unreported-diagnostics list as first argument, and resets the diagnostics list after that call
>   an accessor/resetter to the eglot--unreported-diagnostics list

If you really insist in your implementation, I'm OK with the first bullet, but not with the second.  You should devise the protocol better so that the callback tells Eglot what to do with `eglot--unreported-diagnostics`. It can do this via the return value, for example. That's better than exposing an accessor to an implementation detail.

**Comment by gagbo** [comment]
> This means that as soon as the changes are published Eglot --> Server, flymake _also_ kicks in and puts the correct callback in place, ready to get called as soon as possible. When the diagnostics come in, it _is_ called.

- Oh I didn't know that, good to know :) Also, does this happen on file opening as well ? I guess so because I assume Eglot has to send a message to the server when it starts working on a file, but I don't know LSP well so I'm not sure.

- Even if the latency becomes a non-issue with flymake implementation, there is still the issue that flycheck cannot plug easily onto this because the `report-fn` call is gated by `flymake-mode` and there's no other way to use a reporting function in the current API. _Being able to use a report function with flycheck_ is the sole objective of the PR, even if the discussion got messy (sorry for that)

> If you really insist in your implementation, I'm OK with the first bullet, but not with the second. You should devise the protocol better so that the callback tells Eglot what to do with `eglot--unreported-diagnostics`. It can do this via the return value, for example. That's better than exposing an accessor to an implementation detail.

Sure, I was thinking that the second part would probably rarely be used; but without that, and without a more generic `report-fn`, there's no way to use flycheck with eglot.

An example use case would be to use `pyright` as LSP, and flycheck-pylint or flycheck-flakes simultaneously to get ""type errors"" from pyright and style error from Flakes/Pylint; if there's already a flycheck checker for a lint specific tool (that doesn't exist for flymake) and you want to use LSP for other diagnostics, you kind of have to use flycheck for both. At least, I never managed to have both flymake and flycheck at the same time without a lot of "small things" to fix

**Comment by joaotavora** [comment]
> Being able to use a report function with flycheck is the sole objective of the PR

Then I'm confused again. That's what I'm suggesting! Don't turn on `flymake-mode`. Just pass a "Flycheckish" report-fn to `eglot-flymake-backend` (or to _any_ Flymake backend, as far as I know)  and it will presumably behave well and do the right thing.

**Comment by gagbo** [comment]
It's never called because if we use `flycheck`, then `flymake-mode` is nil and the `cond` branch is [skipped](https://github.com/joaotavora/eglot/commit/da7ff4883d3108468265fdc16a217d8e6aff92f2) in the publishDiagnostics method handler.

So I guess the only solution is to poll it, calling eglot-flymake-backend on a timer, fair enough.

**Comment by joaotavora** [comment]
> `flymake-mode` is nil cond branch is skipped in the publishDiagnostics method handler.

That's a bug, yes.  I can change that.  Assume the `flymake-mode` check isn't there and work out a solution from there.

**Comment by gagbo** [comment]
I created this PR because I assumed the `flymake-mode` check was here to stay.

Without the flymake-mode check in eglot, the code in this PR is not necessary at all. The way it works currently (ignoring the PR) :
- eglot starts and the user asked for flycheck completion (by changing a switch in their Doom config)
- Doom disables flymake
- Doom enables flycheck
- Doom calls `eglot-flymake-backend`, which has the side effect of setting the `report-fn` internal variable
- Eglot receives a `publishDiagnostics`, and as the internal `report-fn` is not nil, it's called and flycheck sets the error properly.

I'll edit this PR to make the above flow clearer (in comments), and I guess we can create an issue on eglot repo just to track when `flymake-mode` check is removed. Would this be ok ?

**Comment by joaotavora** [comment]
> Would this be ok ?

Yes it would.  

Just a nit, it's not "Setting the `report-fn` internal variable", I think you mean `eglot--current-flymake-report-fn`

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the late response. I'll keep an eye on https://github.com/joaotavora/eglot/issues/596. Thanks you both for your help and input!

**Comment by joaotavora** [comment]
And I'm sorry for being late on that issue.  It's just about taking out a single sexp, but it causes some minor bugs that I haven't yet had the time to debug.

**Pull request merged**
