### PR TITLE
Allow +vterm/toggle to open remotely

### PR DESCRIPTION
**Pull request by yangsheng6810**
When `default-directory` is remote, prepare the toggled vterm at remote
location. The added code is taken from `multi-term-switch-buffer` in `multi-term.el`.

### CODE REVIEW

**Comment by yangsheng6810** [comment]
Sure. Where should I put the function in? Assume it should not reside in the `autoload.el`. Maybe corresponding `config.el`?

**Comment by hlissner** [comment]
No, it _should_ be in the autoload.el, perhaps in a general `+vterm--change-directory` function that will change the current directory of the current vterm session (which will additionally handle tramp paths).

**Comment by yangsheng6810** [comment]
It seems `vterm` already handles directory change according to `default-directory` when it is not remote. So I named it `+vterm--change-directory-if-remote.

**Comment by hlissner** [comment]
Thanks!

**Pull request merged**
