### PR TITLE
fix: restore +ivy-buffer-icons config var

### PR DESCRIPTION
**Pull request by rschmukler**
Thanks for all of your amazing work on Doom!

This commit restores the functionality of the `+ivy-buffer-icons`
variable. I tested it in both childframe and regular mode.

### CODE REVIEW

**Comment by rschmukler** [comment]
image

Just including a screenshot to demo what this adds / restores.

**Comment by seanfarley** [comment]
Hey @rschmukler, any chance you can fix the bad rebase on this PR? Thanks!

**Comment by rschmukler** [comment]
@seanfarley sorry on the delay - fixed!

**Comment by hlissner** [comment]
Sorry for the super late followup. There was some cleanup I wanted to do but never got around to them, so I'll merge this for now and get back to it. Thanks for your help!

**Comment by seanfarley** [comment]
image

**Pull request merged**
