### PR TITLE
Bump lsp packages

### PR DESCRIPTION
**Pull request by ericdallo**
lsp-mode did a huge migration to use plists instead of hash-tables.
This PR bump all lsp related projects.

More info here: https://github.com/emacs-lsp/lsp-mode/issues/1751

### CODE REVIEW

**Comment by hlissner** [comment]
3. Also, could you bump `lsp-mode` to emacs-lsp/lsp-mode@7b0b9c3

**Comment by ericdallo** [comment]
Sure!

**Comment by ericdallo** [comment]
Done @hlissner !

**Comment by ericdallo** [comment]
Ops, missing a rename

**Comment by hlissner** [comment]
Great work! Thanks again for your help!

**Pull request merged**
