### PR TITLE
Define lookup handlers for lisp-interaction-mode

### PR DESCRIPTION
**Pull request by flatwhatson**

### CODE REVIEW

**Comment by hlissner** [comment]
Is this necessary? `lisp-interaction-mode` is derived from `emacs-lisp-mode` so it should inherit `emacs-lisp-mode`'s hooks, no?

**Comment by flatwhatson** [comment]
Yes, they do seem to share hooks.  I see both messages when entering `lisp-interaction-mode` with:
```
(add-hook! 'emacs-lisp-mode-hook
           (message "emacs-lisp-mode-hook"))
(add-hook! 'lisp-interaction-mode-hook
           (message "lisp-interaction-mode-hook"))
```

This doesn't seem to affect the lookup handlers though:
```
(progn
  (lisp-interaction-mode)
  +lookup-documentation-functions)
;=> (+lookup-dash-docsets-backend-fn +lookup-online-backend-fn)

(let (funs)
  (emacs-lisp-mode)
  (setq funs +lookup-documentation-functions)
  (lisp-interaction-mode)
  funs)
;=> (+emacs-lisp-lookup-documentation t)

(progn
  (lisp-interaction-mode)
  +lookup-documentation-functions)
;=> (+lookup-dash-docsets-backend-fn +lookup-online-backend-fn)
```

**Comment by hlissner** [comment]
Fair enough. Thanks!

**Comment by flatwhatson** [comment]
Thank you!  <3

**Pull request merged**
