### PR TITLE
Change SPC-g-C to magithub-clone

### PR DESCRIPTION
**Pull request by ar1a**

### CODE REVIEW

**Comment by hlissner** [comment]
Will this work with full git urls?

Also, `magithub-clone` doesn't appear to be autoloaded. Could you add a `:commands (magithub-clone)` to magithub in `:tools magit`?

**Comment by ar1a** [comment]
that's solved with #631

**Comment by ar1a** [comment]
and no, it doesn't support full urls

**Comment by hlissner** [comment]
> that's solved with #631

Not in the case where `magithub-clone` is called before magit has loaded, which the keybind makes a possibility.

**Comment by hlissner** [comment]
> and no, it doesn't support full urls

Hmm, I may hold back on this then. I'll look into the two commands and write a proxy that will accept both full urls and the user/repo format.

**Comment by ar1a** [comment]
pr amended with the autoloaded command

**Comment by hlissner** [comment]
And done. I wrote `+magit/clone` and bound it to `SPC-g-C`.

**Pull request closed without merging**
