### PR TITLE
Add +conda

### PR DESCRIPTION
**Pull request by Emiller88**
Cleaned up from #617. I finally needed it so it got done.

@fuxialexander Would appreciate a README maybe and add anything I missed, please.

### CODE REVIEW

**Comment by Emiller88** [comment]
Unless @fuxialexander says otherwise this should be ready  @hlissner

**Comment by hlissner** [comment]
Nice work @Emiller88 @fuxialexander, this looks great! I'll revisit this once I understand conda better and see if it can be improved.

**Comment by liujoey** [comment]
many issues in this PR.

1. +conda is not loaded in python/config.el. Should add this:
`(if (featurep! +conda)  (load! "+conda"))`

2. `start-pythonic` function doesn't exist, looked around, i believe it belongs to package 'pythonic.el', and the function name has been changed to `pythonic-start-process`

**Comment by Emiller88** [comment]
@liujoey  Feel free to make a PR to my branch or make a new PR to doom with your changes!

**Pull request merged**
