### PR TITLE
org: Update +export to generate revealjs stuff

### PR DESCRIPTION
**Pull request by HaoZeke**
Necessary to not create plain HTML presentations.

### CODE REVIEW

**Comment by HaoZeke** [comment]
With a bit more work this could actually completely replace `ox-reveal`, but that wasn't the point of this.

**Comment by hlissner** [comment]
ox-reveal appears to expose a lot of custom properties and settings. Do these work through pandoc?

Also, what if we _want_ to export plain HTML, would this setting prevent that?

**Comment by HaoZeke** [comment]
@hlissner, 'ox-reveal' is a wrapper around revealJS and 'pandoc' also exposes the exact same set of features, just with a different syntax..

I can duplicate the 'ox-reveal' defaults here too... But for new users 'ox-reveal' is a lot easier so there is no point. 

This does not affect generating 'html', it just ensures that choosing 'revealJS' as the 'pandoc' export target will link to a valid stylesheet. Currently exporting to 'revealJS' with 'pandoc' does not really create a presentation, because it does not link to the 'revealJS' stylesheets or scripts.

**Comment by hlissner** [comment]
Understood. Thanks for the PR!

**Pull request merged**
