### PR TITLE
`doom-file-set-extension`

### PR DESCRIPTION
**Pull request by fosskers**
- [x] It targets the develop branch
- [x] I've searched for similar pull requests and found nothing
- [x] This change is NOT in Doom's do-not-PR list: https://doomemacs.org/d/do-not-pr
- [x] If I've bumped any packages, I've done so according to https://doomemacs.org/d/how2bump
- [x] I've linked any relevant issues and PRs below
- [x] All my commit messages are descriptive and distinct

This PR adds the function `doom-file-set-extension` to its set of other path-related convenience functions.

### CODE REVIEW

**Comment by fosskers** [comment]
CI failing is unrelated to the PR, I think Github is having issues.

**Comment by hlissner** [comment]
Thanks for the PR, but I cannot accept it. Doom doesn't need this function, and it doesn't add anything to its simpler alternative: `(concat (file-name-sans-extension file) ".ext")`. I also don't want Doom to trend any further toward reinventing `f.el` (which has [`f-swap-ext`](https://github.com/rejeep/f.el#f-swap-ext-path-ext)). Sorry for the trouble!

**Comment by fosskers** [comment]
I'll keep it as a local function then, thanks. Figure it was worth sharing.

**Comment by fosskers** [comment]
[Upstreamed](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4f2765f6f1a2cc6da408e3c5ff99ea5f8756bad4).

**Pull request closed without merging**
