### PR TITLE
Fix lispy `j` collision

### PR DESCRIPTION
**Pull request by eugercek**
With evil mode, `j` is used for both `special-lispy-down` and `evil-escape` which is bounded to `evil-escape-key-sequence`, "jk" by default.

A demo:
https://user-images.githubusercontent.com/58051033/127784994-05af014c-b857-41c1-ad10-865f198c42c8.mp4

### CODE REVIEW

**Review by hlissner — CHANGES_REQUESTED** [review]
Please use this instead.

```elisp
(add-hook! 'evil-escape-inhibit-functions
  (defun +lispy-inhibit-evil-escape-fn ()
    (and lispy-mode (evil-insert-state-p))))
```

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks for your help!

**Comment by grios-stratio** [comment]
Hi!

I rather prefer having evil-escape working even with lispy activated. Is there a way to remove this hook in my personal config? (have tried several combinations of `remove-hook` but I don't seem to make it work :sweat:

**Comment by eugercek** [comment]
You can remove the added function with `remove-hook!`.
On my setup this reverts the change added in this PR.
```lisp
(remove-hook! 'evil-escape-inhibit-functions
              #'+lispy-inhibit-evil-escape-fn)
```
But you'll have the bug (https://user-images.githubusercontent.com/58051033/127784994-05af014c-b857-41c1-ad10-865f198c42c8.mp4).

Also you can change the esapce key, to `fj` as an example, with `evil-espace-sequence`
```lisp
(setq evil-escape-key-sequence "fj")
```

**Comment by grios-stratio** [comment]
Thanks! I though I had tried that before without success, but I must have messed something up in the first try :/. Now it is working :)

**Pull request merged**
