### PR TITLE
Add a default set of bindings for non-evil users

### PR DESCRIPTION
**Pull request by UndeadKernel**
If the flag `+bindings` is set in the `default` module, choose a default set of bindings based on whether `evil` is an active module or not.

### CODE REVIEW

**Comment by hlissner** [comment]
Good work!

@jwintz What do you think? (Being an evil user, I'm not a good judge for a non-evil keybinding scheme)

**Comment by UndeadKernel** [comment]
I'm trying to keep this PR updated to the latest develop. It's difficult to keep-up with your updates @hlissner!

Stop commiting for a few minutes! Nah, just a joke. Commit all you can for Skynet needs a descent  operating system that is connected to planet mars and hell :D

**Comment by hlissner** [comment]
@UndeadKernel Quite right! The travis tests are fixed now.

I've slated the merge for this PR for 2.1.1 now that 2.1 is just on the horizon, but I look forward to including it in Doom!

**Comment by Oghma** [comment]
I believe the org section should be
```emacs-lisp
;; Org related bindings
 (:prefix "C-c o"
   "s"     #'org-caldav-sync
   "a a"   #'org-agenda
   "a t"   #'org-todo-list
   "a m"   #'org-tags-view
   "a v"   #'org-search-view
   "c"     #'org-capture
   "C"     (λ! (require 'org-capture) (call-interactively #'org-capture-goto-target))
   "b"     #'org-iswitchb
   "e l b" #'org-beamer-export-to-latex
   "e l B" #'org-beamer-export-as-latex
   "e l P" #'org-beamer-export-to-pdf
   "l"     #'org-store-link)
```

**Comment by UndeadKernel** [comment]
@Oghma You are indeed correct. I'll fix it tomorrow.

**Comment by hlissner** [comment]
[A non-evil keybinding scheme #641](https://trello.com/c/TP5Yf7Ls/17-a-non-evil-keybinding-scheme-641)

**Comment by seanfarley** [comment]
Oh, wow, I just found this (and am glad because I was about to duplicate some of this work)! Is there any way to get this PR picked up again possibly?

**Comment by UndeadKernel** [comment]
We are waiting for @hlissner to give us the "go ahead" to continue working
on this default scheme.

Though, I'd be glad to update this PR with more bindings and to follow the
latest commits.

Also, if you have more suggestions for default key bindings, let me know
and I'll add them here.

**Comment by seanfarley** [comment]
Ah, makes sense, @UndeadKernel thanks~! I'm just now switching from my handcrafted lisp to doom so it'll take a bit to adjust to these keybindings (though from reading them they look great).

**Comment by UndeadKernel** [comment]
I created another pull request as a follow up to this one.

**Pull request closed without merging**
