### PR TITLE
Add keybindings for circe

### PR DESCRIPTION
**Pull request by MarkRedeman**
This PR adds `SPC o I` as a keybinding to open IRC. When in a `circe` buffer some additional keybindings are available to make it easier to switch channels and sent private messages.

I also added an example of a pass entry to the documentation.

### CODE REVIEW

**Comment by bandresen** [comment]
Very nice!

**Comment by hlissner** [comment]
This looks great. Although, I have issue with the `SPC o I` keybinding. All app keybinds were removed not so long ago. The expected way to open them is through `M-x`, because:

+ Activating an app module is a drastic context shift and was too close to other less imposing keys like opening eshell, term, dired or neotree.
+ Part of the reason why app "launcher" commands were given a unique prefix (`=twitter`) was so they would be easy to locate and isolte in the `M-x` menu.

I may add a `SPC o =` prefix for apps later, but for the time being, could you remove the keybind?

**Comment by MarkRedeman** [comment]
That makes sense. Having a `SPC o =` prefix would be nice as it helps the discoverability of the apps (when switching from Spacemacs to Doom it wasn't immediately obvious how to use the IRC module).
For now I've removed the keybinding and made a note about starting IRC using `=irc` in the documentation.

**Comment by hlissner** [comment]
Excellent work. Thanks again!

**Pull request merged**
