### PR TITLE
ligatures/pragmata: Update ligature table for pragmata 0.829

### LINKED ISSUE #5358: Pragmata ligatures are incorrectly mapped for pragmata 0.829
### What did you expect to happen?

When I use pragmata ligatures, I expect it to use the correct ligature symbol.

### What actually happened?

After upgrading to pragmata 0.829, ligatures are messed up.

[Example](https://ibb.co/gvdxF2h)

### Describe your attempts to resolve the issue

PR incoming

### Steps to reproduce

1. Install pragmata pro
2. Enable ligatures +pragmata module
3. Test ligatures such as [[ ]] && etc...

### System Information

https://pastebin.com/nWcK1WL6

### PR DESCRIPTION
**Pull request by Tomahna**
Fixes #5358 

Updating ligature table with new unicode codes for ligatures. This is drawn from https://github.com/lumiknit/emacs-pragmatapro-ligatures/blob/master/pragmatapro-lig.el.

### CODE REVIEW

**Comment by bronislav** [comment]
This does not work for me. I just replaced original file with file from this PR and ligatures still broken but in a different way.

**Comment by Tomahna** [comment]
Hey, thanks for trying this out.

Just to check, do you have PragmataPro 0.829 ? Can you check the sha256sum of the zip you downloaded from fsd.it just to be sure that we have the same version ?

```
~ sha256sum PragmataPro0.829.zip
553c490067c2bc655d517c7648a099304cc84b580b703bbea1d65924cff33461  PragmataPro0.829.zip
```

**Comment by bronislav** [comment]
@Tomahna you are right I did have wrong version for some reason. I tested archive and it's sha didn't match. I download it again and it shown correct sha now:

```
❯ sha2 -256 ~/Downloads/PragmataPro0.829
SHA-256 (PragmataPro0.829) = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

❯ sha2 -256 ~/Downloads/PragmataPro0.829\(1\).zip 
SHA-256 (PragmataPro0.829(1).zip) = 553c490067c2bc655d517c7648a099304cc84b580b703bbea1d65924cff33461
```

I reinstalled font and restarted emacs, but some(most) ligatures are not correct anyway.

**Comment by bronislav** [comment]
`C-u C-x =` shows me that wrong ligatures are from all-the-icons font. Not sure why it is messing with my ligatures. I thought it should be used only for icons when specifically requested.

**Comment by Tomahna** [comment]
Not sure it is linked to your issue. But I have indeed messed up ligatures when I go to doom-big-font-mode (even while having pragmata pro defined as doom-big-font).

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks for your help!

**Pull request merged**
