### PR TITLE
replace deprecated rustic-format-on-save in rust readme

### LINKED ISSUE #5740: documentation is wrong about format +onsave with rust
### What did you expect to happen?

When I enable (format +onsave) in init.el, rust files should be formatted on save.
The documentation states that no additional configuration is necessary.

### What actually happened?

Rust files were not formatted on save.

### Describe your attempts to resolve the issue

Adding
``` elisp
(after! rustic
    (setq rustic-format-on-save t))
```
to config.el did work.

### Steps to reproduce

1. Open init.el
2. uncomment (format +onsave)
3. edit a .rs file in a rust project
4. save it

### System Information

https://pastebin.com/YahxaaJP

### PR DESCRIPTION
**Pull request by brotzeit**
close #5740

### CODE REVIEW

**Comment by brotzeit** [comment]
It has become quite difficult to get something merged here =)

**Comment by gagbo** [comment]
rebasing on top of current develop and running `doom ci lint-commits HEAD` will help

**Comment by brotzeit** [comment]
@gagbo thanks!

**Comment by hlissner** [comment]
Docs are currently undergoing a rewrite. That's why it's in [our do-not-pr](https://discourse.doomemacs.org/t/development-roadmap/42#do-not-pr) list.

**Comment by hlissner** [comment]
> It has become quite difficult to get something merged here =)

That's what happens when the project leads goes on a health sabbatical for two months. I'm back now. Please be patient.

**Comment by brotzeit** [comment]
> That's what happens when the project lead goes on a health sabbatical for two months.

I don't mean the waiting time, I just opened the pull request. I was referring to the linter. But it was no complaint, I can understand the reasons. However it's interesting to see the changes if you only open a pull request once a year ;)

**Pull request closed without merging**
