### PR TITLE
[FEATURE] Add :ui hydra README

### PR DESCRIPTION
**Pull request by gagbo**
This is mostly a stub, the keybindings are just the one I chose for my own usage, I don't know if there are better choices or not :(

- [x] ~~evil keybindings~~
- [ ] ~~emacs keybindings~~
- [x] README added

### CODE REVIEW

**Comment by hlissner** [comment]
I'm still on the fence about hydra keybinds, and not too keen to add a new leader prefix for a single key. For the time being, please remove them. There already exist font size commands on `C-=` and `C--` for buffer-local resizing, `M-C-=` and `M-C--` for frame-local. I'll happily accept the README though.

**Comment by gagbo** [comment]
Fair enough, I wasn't sure since it was a little confidential

**Comment by hlissner** [comment]
Thanks for the help!

**Comment by myrgy** [comment]
@gagbo ,
> Fair enough, I wasn't sure since it was a little confidential
I realised, that bindings file is the best README for now)
https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el

**Comment by gagbo** [comment]
> @gagbo ,
> 
> > Fair enough, I wasn't sure since it was a little confidential
>
> I realised, that bindings file is the best README for now)
> https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el

Oh yeah for sure, what I meant is that the hydras defined in the module (hydra/window-nav and hydra/text-zoom) aren't bound at all (in modules/hydra/config.el or +*-bindings.el). The only way to know about those was to actually go in the `config.el` file of the module :)

**Pull request merged**
