### PR TITLE
Add lsp support to sh module.

### PR DESCRIPTION
**Pull request by dinkonin**

### CODE REVIEW

**Comment by gagbo** [comment]
Can you add the dependencies for the server too in the README ? (thanks for adding that by the way !)

I don't know which servers are replying to requests for shell files

**Comment by dinkonin** [comment]
I need a little clarification about this change request, what exactly should I add to README. In the original PR I've already added `bash-language-server` to the list of of dependencies. Should I add a link to the `bash-language-server` repo?

**Comment by hlissner** [comment]
Ah, I've just realized that lang/sh's README hasn't been updated to the new format. In that case I'll accept the PR as is and reformat it myself later.

I'll merge once I get home later tonight.

**Comment by gagbo** [comment]
>  I've already added `bash-language-server` to the list of of dependencies.

My bad, I definitely missed the line since I was expecting a hefty org link in the change

**Comment by hlissner** [comment]
Thanks for your help!

**Pull request merged**
