### PR TITLE
[javascript] add prettier-js support

### PR DESCRIPTION
**Pull request by danielpa9708**
support formatting with prettier https://github.com/prettier/prettier, https://github.com/prettier/prettier-emacs

### CODE REVIEW

**Comment by hlissner** [comment]
I'm afraid I cannot accept this PR, because it is redundant with the `:editor format` module (and its +onsave flag), which uses prettierjs by default and is the canonical way to enable code formatters in Doom. That said, I'm aware that this module lacks documentation and it is overdue for a rewrite; I'm working on it. In any case, thanks for the PR and for bringing it to my attention.

**Comment by danielpa9708** [comment]
Ok, wasn't aware of it. I'll see what I can do to integrate `:editor format` with prettier in my config

**Comment by AlexXiong97** [comment]
@danielpza do you have any idea how to have the prettier read from `.prettierc` config for each project with `:editor format` enabled? thanks

**Comment by danielpza** [comment]
@AlexXiong97 I think it already does. I don't get what you are trying to do? Do you want to format with prettier only if the project has a .prettierrc ?

**Comment by AlexXiong97** [comment]
@danielpza sorry, you are right. It already does.

**Comment by alrayyes** [comment]
Is there any special extra setup for this? When i run `+format/buffer` using `org-edit-special` I get the following error:

`Don't know how to format js-mode code`

As far as i can tell formatting works properly with full TypeScript files.

**Pull request closed without merging**
