### PR TITLE
Add lsp and repl to +light modeline

### PR DESCRIPTION
**Pull request by ericdallo**
This PR improves `+light` modeline:
* Checks for LSP status 
* Checks CIDER if enabled for clojure buffers.

I used the same :rocket: icon from `doom-modeline`, but if you think that makes sense change to another, let me know it.
image

Just following the [idea from doom modeline](https://github.com/seagle0128/doom-modeline/issues/347), when CIDER is available/connected/disconnected we show an icon:
image

### CODE REVIEW

**Comment by hlissner** [comment]
Could you have each particular module add a segment to `global-mode-string`, rather than add segments to the modeline?

**Comment by ericdallo** [comment]
@hlissner do you mean `setq` `global-mode-string` on `:lang clojure` and `:tools lsp` modules?

**Comment by ericdallo** [comment]
@hlissner just followed your suggestion, but it seems that the colors are not working via the `global-mode-string`:
image
Do you think what could it be?

**Comment by ericdallo** [comment]
Ping. @hlissner

**Comment by ericdallo** [comment]
@hlissner Fixed all issues, now it is working as expected:
image

**Comment by ericdallo** [comment]
@hlissner could you take a look at this, please?

**Comment by thiagokokada** [comment]
@hlissner

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the late response. This looks good to me, thanks!

**Pull request merged**
