### PR TITLE
refactor(biblio): update citar config

### PR DESCRIPTION
**Pull request by bdarcus**
- Remove outdated config for org-roam.
- Set org-cite-bibliography to citar-bibliography

### CODE REVIEW

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks again for your help!

**Comment by prashantnag93** [comment]
@bdarcus after this upgrade I am getting the following error: 
```
      Message: Symbol's value as variable is void
      Error: (void-variable citar-bibliography)
```

**Comment by hwiorn** [comment]
@bdarcus I have the same error too.

**Comment by dschrempf** [comment]
I can also confirm this error.

**Comment by bdarcus** [comment]
> @bdarcus after this upgrade I am getting the following error:
> 
> ```
>       Message: Symbol's value as variable is void
>       Error: (void-variable citar-bibliography)
> ```

Ugh; sorry about that.

@hlissner - I think you can just remove this:

https://github.com/hlissner/doom-emacs/blob/ff4609835a4c47312b3d685e09330034d6f4c8a4/modules/tools/biblio/config.el#L26

Do you want to do that, or would you like a separate PR?

**Comment by hlissner** [comment]
No worries! I've removed it in 265afc9, so the issue should be resolved.

**Pull request merged**
