### PR TITLE
fix a break change in vterm.el,  (+vterm/here) can't create new terminal any more without this pr

### PR DESCRIPTION
**Pull request by jixiuf**
see https://github.com/akermu/emacs-libvterm/issues/505

I am not a doom user , maybe this is not a best fix, but it works .

### CODE REVIEW

**Comment by gagbo** [comment]
Note: the change is 5 commits _after_ current pin https://github.com/akermu/emacs-libvterm/commits/c2c2c8afb935c11778388721912250cd1103aaf9

**Comment by hlissner** [comment]
Thanks for the PR, but I must turn it down (for now). This module will be bumped soon along with other changes to the `:term` modules. I will include this one when that happens.

**Comment by ra1nb0w** [comment]
I don't see this merged; Can be merged? thank you

**Comment by Dieken** [comment]
this is included in https://github.com/hlissner/doom-emacs/pull/4836, but it’s also not merged😓

**Pull request closed without merging**
