### PR TITLE
Bump ddskk

### PR DESCRIPTION
**Pull request by JordanAnthonyKing**
w.r.t https://github.com/skk-dev/ddskk/issues/190 
Bump ddskk version to include fix.

### CODE REVIEW

**Review by hlissner — CHANGES_REQUESTED** [review]
Bump commits must follow strict formatting to be machine readable by future CI. Please reword the commit to:

```
Bump ddskk

skk-dev/ddskk@cec9936 -> skk-dev/ddskk@6ed5184

Bump ddskk to include fix for skk-dev/ddskk#190
```

**Comment by JordanAnthonyKing** [comment]
Once skk-dev/ddskk#190 is resolved I'll squash and update the message.

Thanks.

**Comment by JordanAnthonyKing** [comment]
@hlissner https://github.com/skk-dev/ddskk/issues/190 has been resolved

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the late response. Thanks for your help (on this PR and the upstream issue)!

**Pull request merged**
