### PR TITLE
bump :lang rust

### PR DESCRIPTION
**Pull request by brotzeit**
brotzeit/rustic@804ebfe -> brotzeit/rustic@eb5ca14

### CODE REVIEW

**Comment by andresilva** [comment]
This breaks ligatures on `->` for me. I've bisected rustic and nailed down the breaking change to this commit: https://github.com/brotzeit/rustic/commit/1441f1d4675aefbe7d32b8be3c05fac4ece43461. I guess the next step would be to depend directly on `rust-mode` and bisect it as well, I haven't done this yet.

**Comment by brotzeit** [comment]
@andresilva thanks for testing. The issue is that rustic was a fork for years and we must have applied some changes to either rust-mode or rustic in this time that broke or fixed this issue. If you could take a look at rust-mode would be great, I'll also take a look and try to find the commit that contains the related change.

**Comment by brotzeit** [comment]
Maybe this one  https://github.com/rust-lang/rust-mode/commit/959bfce215c342c83d72650b2b35201de263edfe ?

**Comment by andresilva** [comment]
I was just writing that! Yes, that's the commit that broke it for me, thankfully I can just override `rust-prettify-symbols-alist` to `nil` to use the ligatures I have setup. I looked at `rust-mode.el` before bisecting but somehow missed this, it was obvious in hindsight 😜

**Comment by brotzeit** [comment]
=)

I guess you can't push to my branch so I'll add the fix

**Pull request closed without merging**
