### PR TITLE
Add clock bindings under `n C`

### PR DESCRIPTION
**Pull request by rgrinberg**
org-clockout
org-clock-goto
org-clock-cancel

### CODE REVIEW

**Comment by rgrinberg** [comment]
@hlissner ping on this PR. It's quiet useful for those work with clocks.

**Comment by hlissner** [comment]
Sorry for the late response. I'm pretty swamped at the moment. I'm not a fan of capitals as prefixes (they're easy to mess up), so I've been looking for alternatives. Currently experimenting with:

+ `SPC t c` = `+org/toggle-clock`
+ `SPC t C` = `org-clock-cancel`
+ `SPC n o` = `org-clock-goto`

But I haven't decided yet. I'll get back to you soon.

**Comment by rgrinberg** [comment]
No worries, I’ll ping you if you can’t make up your mind in a month :)

**Comment by hlissner** [comment]
I've decided to put it on `SPC n {c,C,o}`. I think the notes prefix makes the most sense for it.

**Pull request closed without merging**
