### PR TITLE
added company-files support for file links in org mode

### PR DESCRIPTION
**Pull request by JakDar**
Added regex for company-files to recognize file links in org-mode.
I can move changing `company-files-regexps` if there is better place to modify it.

### CODE REVIEW

**Comment by JakDar** [comment]
Moved adding regexp to org/config.el and removed escaping `:` ;)
I couldn't use `setq-hook!`, because `company-files` had to be required so that `company-files-regexps` is in scope.

**Comment by hlissner** [comment]
> I couldn't use setq-hook!, because company-files had to be required so that company-files-regexps is in scope.

My bad, forgot about the variable reference in the new value. 

That said, I'd really like to avoid: 1) a quoted, closure for a hook, 2) eagerly loading company when org-mode loads, and 3) setting `company-files--regexp` globally, rather than buffer-locally.

Unfortunately, company's unusual lazy-loading makes achieving all of the above a bit difficult. I'll look into it.

**Comment by JakDar** [comment]
If copying initialization of `company-files-regexps` is an option i might have a beginning of solution (removed eager loading and closure in a hook), but I still don't know how to make it buffer-local.

**Comment by hlissner** [comment]
> but I still don't know how to make it buffer-local.

With `setq-local`, rather than `setq`.

> If copying initialization of company-files-regexps is an option

Perhaps we can avoid that with:

```elisp
(defun +org-init-company-h ()
  (after! company-files
    (setq-local company-files--regexps
                (cons "file\:\\(\\(?:\\.\\{1,2\\}/\\|~/\\|/\\)[^\]\n]*\\)"
                      company-files--regexps))))
```

**Comment by JakDar** [comment]
Just made a change.

**Comment by hlissner** [comment]
Great, thanks for the quick responses (and for putting up with me)!

**Pull request merged**
