### PR TITLE
Add xterm-color to improve colour support

### PR DESCRIPTION
**Pull request by elken**
Similar to the last PR, this attempts to add even better colour support. Currently trying to break it but seems to fix most of them.

https://i.imgur.com/35dhkJl.png

Do you think this should be behind a flag?

### CODE REVIEW

**Comment by hlissner** [comment]
Can you show a before screenshot? `rg` output seems correctly colored without.

image

Partly because [of our `rg` alias](https://github.com/hlissner/doom-emacs/blob/develop/modules/term/eshell/config.el#L32).

**Comment by elken** [comment]
`rg` is a bad example then xD I will find a few tonight

**Comment by elken** [comment]
image

It's mostly triggered with the `doom` cli from what I can see, a few others here and there

**Comment by hlissner** [comment]
Did you figure it a fix? Is this PR safe to close?

**Comment by elken** [comment]
The only one I could see was add the hook back and set TERM to `eshell-term-name`, or use this PR

**Pull request closed without merging**
