### PR TITLE
nit: typo, taureg -> tuareg

### PR DESCRIPTION
**Pull request by glennsl**

### CODE REVIEW

**Comment by jeetelongname** [comment]
please try and conform to out git conventions which can be found [here](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854)

**Comment by glennsl** [comment]
Sorry, I did look at the conventions and tried to conform to it. Even after reading the lint error and going over the conventions again, I still can't figure out what's actually wrong. The amount of time I'm willing to invest in fixing a silly typo has already been exceeded, so I'll just close this. I'm sure you'll be able to fix this on your own if you really want to.

**Comment by jeetelongname** [comment]
the tldr is that you did not use a proper type and scope, so 
`nit(core): correct tuareg typo` should pass the linter but ill PR a fix, thanks you anyway!

**Comment by glennsl** [comment]
Ah, sorry, I see now that I just fixed the PR subject, not the actual commit message. The error makes much more sense now!

**Pull request closed without merging**
