### PR TITLE
Fix nil issue with nav-flash & ivy

### PR DESCRIPTION
**Pull request by elken**
Raised on discord, without this causes issues with ivy in most cases. (sorry about the dirty commits)

### CODE REVIEW

**Review by hlissner — CHANGES_REQUESTED** [review]
Rather than create an overlay, it'd be better not to call `overlay-put` at all. Please wrap it in a 

```lisp
(when (overlayp compilation-highlight-overlay)
  ...)
```

Also, please rebase (squash and force-push) this PR into a single commit.

**Comment by elken** [comment]
True, yeah I'll change. I did try but it wasn't having it and I didn't expect it to bomb out.

**Comment by elken** [comment]
All good! Apologies, haven't had to do a rebase for a while.

**Comment by hlissner** [comment]
No worries. Thanks for the help!

**Pull request merged**
