### PR TITLE
use default search on rake tasks on :ruby lang

### PR DESCRIPTION
**Pull request by otavioschwanck**

### CODE REVIEW

**Comment by hlissner** [comment]
Can you explain what this does and why it's being changed?

**Comment by otavioschwanck** [comment]
> Can you explain what this does and why it's being changed?

with this, it will use the doom default search instead ido

**Comment by sei40kr** [comment]
@hlissner 
FYI, we don't need Rake anymore because taskrunner supports it.

`rake` -> `+taskrunner/project-tasks`
`rake-rerun` -> `(ivy|helm)-taskrunner-rerun-last-command`

**Comment by hlissner** [comment]
@sei40kr That's true. I'll merge this for the time being, but I'll look into substituting rake for taskrunner soon.

**Pull request merged**
