### PR TITLE
Add org-roam doctor check for the dot executable

### PR DESCRIPTION
**Pull request by yoavm448**

### CODE REVIEW

**Comment by yoavm448** [comment]
Actually, let me change the phrasing

**Comment by Emiller88** [comment]
What about if users are using neato? Just a thought, but I think the doctor warning that the default won't work is enough, and we don't need to cover users who read the docs and figured out the switch.

**Comment by hlissner** [comment]
Thanks!

> What about if users are using neato?

I could change it later to check `org-roam-graph-executable` instead of `"dot"`.

**Comment by yoavm448** [comment]
I don't think this is a huge issue, since neato is usually packaged with dot in graphviz, but covering all cases is probably best.

**Pull request merged**
