### PR TITLE
Add latex env support to editor/fold with hideshow

### LINKED ISSUE #2805: Use TeX-fold in +fold/toggle for TeX documents
Currently in TeX documents, +fold/toggle folds using hideshow folds. It would be nice if we could get it to use TeX-fold. This is by default bound to C-c C-o C-o. 

**System information**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop e5ac4cbff 2020-03-29 01:31:27 -0400
        dir        ~/.config/dotfiles/doom_emacs/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/sh
        uname      Linux 5.5.13-arch1-1 #1 SMP PREEMPT Wed, 25 Mar 2020 16:04:40 +0000 x86_64
        path       (/opt/omnisharp-roslyn/ ~/.bin/ ~/.emacs.d/bin ~/.emacs.d/bin ~/.local/bin ~/.bin /usr/local/bin /usr/local/sbin /usr/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion (ivy +icons +prescient +fuzzy) (company +auto) :ui doom modeline ophints hl-todo nav-flash treemacs (popup +all +defaults) (pretty-code +fira) vc-gutter vi-tilde-fringe window-select hydra zen :editor (evil +everywhere +commands) snippets file-templates multiple-cursors rotate-text fold format :emacs (dired +icons) vc :tools lookup eval make magit (lsp +peek) editorconfig pdf ein :lang (sh +fish) emacs-lisp markdown (haskell +lsp) (org +attach +babel +export) (cc +lsp) ocaml idris (web +html +css) (latex +latexmk +viewers) (python +lsp) (fsharp +lsp) (javascript +lsp) rest data :checkers grammar spell (syntax +childframe) :term vterm eshell)
        packages   ((vimrc-mode) (alloy-mode :recipe (:host github :repo dwwmmn/alloy-mode)) (fill-column-indicator) (hugo :recipe (:host github :repo aaronbieber/hugo.el)) (evil-snipe :disable t) (rebecca-theme))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

### PR DESCRIPTION
**Pull request by yoavm448**
Yet another LaTeX PR...

Closes #2805. See it for a screenshot.

### CODE REVIEW

**Comment by UndeadKernel** [comment]
Another nice thing to have, yet tricky to implement, is a folding mechanism for sections, paragraphs, chapters, etc...

For example, if folding a section, you could fold from the first instance of `\section` until before another `\section` or the end of the file.

**Comment by yoavm448** [comment]
Auctex supports outline - you just need to activate `outline-minor-mode` to have exactly that!

Should I add a hook to activate it automatically?

**Comment by yoavm448** [comment]
Regarding the difference with TeX-fold, there's not much. This implements it with hideshow, so `:editor fold` can target the envs. And it looks a little different.

**Comment by hlissner** [comment]
Looks good to me! Thanks again for the help!

**Pull request merged**
