### PR TITLE
Fix #4736 - remap insert state bindings in minibuffer maps

### LINKED ISSUE #4736: swiper-isearch key binding issue (no selection of previous item) with layout bepo
**What did you expect to happen?**
The key-binding for selecting the previous item in swiper isearch with layout bepo (`C-s`) would select it.

**What actually happened?**
The next item is selected, as when typing `C-t`.

**Steps to reproduce:**
1. Configure `:input (layout +bepo)` in `init.el`
2. Launch `swiper-isearch` (through `+default/search-buffer`, `SPC s s`)
2. type some text that occurs several times in the buffer
3. select the next item using `C-t`
4. try selecting the previous item using `C-s`, and observe it actually selects the next one

**System information:**
<details><pre>
```
SYSTEM  info       ("Arch Linux" . Linux 5.11.2-arch1-1 x86_64)
        shell      /bin/zsh
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.opam/4.10.0/bin ~/bin ~/go/bin ~/.opam/4.10.0/bin ~/.nvm/versions/node/v10.21.0/bin ~/bin ~/go/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    (27.1 Aug 28, 2020)
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    (2.0.9 HEAD -> develop 5d9efe89b 2021-03-04 16:42:27 -0500)
        font       #<font-spec nil nil Iosevka nil nil nil nil nil 32 nil nil nil nil>
        theme      leuven
        modules    (:input (layout +bepo) :completion (company +childframe) (ivy +icons) :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs (dired +icons) electric undo vc :term eshell :checkers syntax (spell +flyspell) :tools (eval +overlay) lookup magit make (pass +auth) pdf :lang coq data emacs-lisp javascript latex ledger lua markdown ocaml (org +gnuplot +roam +noter +pretty) sh :email notmuch :app calendar irc (rss +org) :config literate (default +bindings +smartparens))
        packages   ((ebdb) (emojify) (org-review) (xah-replace-pairs) (org-ref) (gnuplot) (ts) (magit-todos :disable t) (elpher) (org-roam-bibtex) (leuven-theme) (unicode-fonts) (beacon) (xah-math-input) (lexic :recipe (:host github :repo tecosaur/lexic)))
        unpin      (org-ref)
        elpa       (n/a)
```
</pre></details>

### PR DESCRIPTION
**Pull request by gagbo**
- Run `doom-bepo--evil-collection-hook` on all minibuffer maps. This
  allows all bindings in <insert-state> to be remapped in minibuffer
  contexts
- Unmap `swiper-C-s`

### CODE REVIEW

**Review by hlissner — APPROVED** [review]

**Comment by brabalan** [comment]
I’m giving this a try and the `C-s` binding in `swiper-isearch` has an issue, it seems to call `isearch-forward` instead of selecting the previous candidate.

**Comment by gagbo** [comment]
I'll test again but it's likely to be a `swiper` issue.

`swiper-isearch-map` has [only swiper-map](https://github.com/abo-abo/swiper/blob/e005666df39ca767e6d5ab71b1a55d8c08395259/swiper.el#L1539-L1544) as parent, and `swiper-map` has [no parent](https://github.com/abo-abo/swiper/blob/e005666df39ca767e6d5ab71b1a55d8c08395259/swiper.el#L144-L153)

So `C-s` bubbles up to global-map directly where it's isearch-forward. I don't know why there's no minibuffer map in-between, and I don't know enough of swiper/ivy internals to see why/how `next-line` and `previous-line` are supposed to be handled there.

**Comment by brabalan** [comment]
Could it be defined in evil collection? There is an ivy file there (https://github.com/emacs-evil/evil-collection/blob/master/modes/ivy/evil-collection-ivy.el), but I do not see bindings for `C-j` or `C-k`.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Looks good to me. Thanks for your help!

**Pull request merged**
