### PR TITLE
Remove lispy from evil-collections

### PR DESCRIPTION
**Pull request by rgrinberg**
The bindings that it creates are weird and conflict with lispyville's
own bindings.

### CODE REVIEW

**Comment by JSDurand** [comment]
Adding 
```lisp
(after! (evil-collection lispy)
  (lispy-set-key-theme '(special lispy)))
```
to the .doom.d/config.el fixes the problem for me.

**Comment by rgrinberg** [comment]
What problem does it fix for you?

**Comment by JSDurand** [comment]
I can use the lispy keybindings again.

**Comment by rgrinberg** [comment]
What does it have to do with disabling evil collections for lispy?

**Comment by JSDurand** [comment]
Since you said the bindings by evil-collection are weird, I think it may help to set the theme to use the bindings not created by evil-collection.

**Comment by rgrinberg** [comment]
Okay, thanks, now I see what you mean. However, I still think that this isn't optimal. It seems like evil collections for lispy essentially conflicts with lispyville. Consider bindings like `M-(` which are bound both by lispyville and evil-collection's lispy. I think that these styles are mutually exclusive and we should either:

* pick one style in the lispy module
* give users the choice using some config

Having this workaround doesn't give a good user experience out of the box.

**Comment by hlissner** [comment]
The relationship between evil-collection-lispy, lispy and lispyville isn't clear to me. I'll look into it after the holidays. In the meantime you can add symbols to `+evil-collection-disabled-list` to disable their respective evil-collectio module.

```elisp
(add-to-list '+evil-collection-disabled-list 'lispy)
```

**Comment by rgrinberg** [comment]
done

**Comment by hlissner** [comment]
Great! Thanks again!

**Pull request merged**
