### PR TITLE
bindings: update bindings / add remote bindings

### PR DESCRIPTION
**Pull request by UndeadKernel**
Update emacs bindings to match recent evil bindings.
Remove the `g` (lookup) prefix and merge those bindings onto the `s` prefix (just like in the evil bindings).

Add more `remote` bindings for emacs and evil users.

### CODE REVIEW

**Comment by hlissner** [comment]
How do vanilla users invoke the `+lookup/definition` or `+lookup/references` commands? Is that an oversight or are there other keybinds? I know `+lookup/definition` has `M-.` (remapped from `xref-find-definitions`), but not sure about `+lookup/references`.

**Comment by UndeadKernel** [comment]
The standard key binding for `+lookup/references` in vanilla emacs is `M-?`, which is normally bound to `xref-find-references`.

In current Doom emacs, `+lookup/references` is correctly bound to `M-?`.

**Comment by hlissner** [comment]
Understood. Oh, seems another PR caused a conflict. Could you rebase this PR to resolve it?

**Comment by UndeadKernel** [comment]
Rebased and ready :D

**Comment by hlissner** [comment]
Nice work. Thanks again!

**Pull request merged**
