### PR TITLE
python +lpy +conda; org +ipython

### PR DESCRIPTION
**Pull request by fuxialexander**
This PR adds a workflow to work with ipython in org-mode, which is particularly useful for data science. `lpy` and `conda` support were added to help python editing experience. (Conda is used more often than pyenv in data analysis using python).

Main features including:
1. Right pane for edit / run python codes
2. Painless remote ipython kernel support
3. Enjoyable lispy-like python editing experience provided by `lpy` from @abo-abo .
4. Everything are integrated together (conda, lpy, python-send-*, ob-ipython)
5. TRAMP support for `conda.el` (which regulates `anaconda-mode` and `lpy` to use correct python interpreter)

Demo:
1. Remote file with `anaconda-mode` setup to display doc for remote module. Also `conda env` is shown in modeline
image

2. `org-edit-src` setup code editing panel and REPL automatically. Also work for remote kernel.
image

3. Run code in REPL use `+python/repl-send-dwim` or `e` in `lpy`.
image

4. Remote-kernel-based completion works (through lpy `C-x C-o`).
image

### CODE REVIEW

**Comment by digizeph** [comment]
Wow, this looks amazing!

**Comment by hlissner** [comment]
This looks fantastic, but there are a few issues:

1. There are private customizations sprinkled in (such as your `+python-conda-home` entries),
2. This change aggressively removes pyenv support, rather than disabling it or detecting one or the other.
3. I'm hesitant to accept lpy-mode, as I think it creeps into personal preference territory.
4. A few naming conventions aren't being followed (particularly where advice functions are concerned) (a minor nitpick).

In any case, the lang/python module has been asking to be rethought for a while so I will look into this as soon as 2.1 is on master. I may end up rewriting it with this PR as inspiration for pyenv, conda, virtualenv, and ipython support, including pipenv support.

**Comment by Emiller88** [comment]
Causes an error for me `Error (use-package): org-gcal/:catch: Symbol’s function definition is void: ivy-add-actions`

@hlissner  can we make an issue to discuss the python rewrite and get input in one spot?
I also agree(though I would personally use this package) that it creeps into personal preference. Which gives me the idea that maybe we need some way to have an archive of cool personal private modules. Maybe I'll make a repo of private modules that people have made that are awesome but don't really fit the majority of users.

**Comment by hlissner** [comment]
@Emiller88 I agree. I've already created a list of Doom configs in the new documentation. I'll link to it once it's up.

As for the python rewrite, there's #358, but I'll get back to you on that once I'm closer to 2.1.1. I've broken out of pyenv for pipenv, virtualenv and conda for my ML work and will learn more about it before I make any decisions.

**Comment by fuxialexander** [comment]
Thanks for your comments! I'll try separate the lpy code from the main body. Plus I think maybe I should try to PR to some of those packages instead of constantly accumulating :override 😂😂😂

**Comment by UndeadKernel** [comment]
It's not only python that we are addressing here.
`ob-ipython` is the main reason for this PR. This is a feature that would be most welcome in DOOM.
I'll be testing this code tomorrow @fuxialexander. Thank you.

**Comment by fuxialexander** [comment]
Sure! I agree with you.

**Comment by fuxialexander** [comment]
Let me close this PR and reopen one for ob-ipython.

**Comment by fuxialexander** [comment]
Let me close this PR and reopen one for ob-ipython.

**Comment by abo-abo** [comment]
@fuxialexander I'm glad `lpy` is getting some use. Feel free to PR your improvements.

**Comment by fuxialexander** [comment]
@abo-abo  Sure! Will do that this weekend!

**Pull request closed without merging**
