### PR TITLE
Add LSP support for YAML

### PR DESCRIPTION
**Pull request by sei40kr**
## Description

* Move `yaml-mode` in `data` to a new module `yaml`
* Enable LSP for `yaml-mode` if `+lsp` is present, which enables:
  * code completion
  * documentation
  * diagnostics
    (these are based on schemas downloaded by [JSON Schema Store](http://schemastore.org/json)).

### CODE REVIEW

**Comment by hlissner** [comment]
Is there any reason this couldn't have been done within the `:lang data` module? I don't think this yaml module is large enough to warrant its own module.

**Comment by sei40kr** [comment]
@hlissner 
It's because we may have LSP on another data language (e.g. json) in the future.
Also I thought giving `+lsp` to `data` module to enable LSP on `yaml-mode` is a little bit confusing.

**Comment by yoavm448** [comment]
Maybe enable lsp for yaml with a `+lsp-yaml` flag under `:lang data`?

**Comment by sei40kr** [comment]
@yoavm448 Thanks for your opinion.

@hlissner 
I've updated the PR. Please review.

**Comment by yoavm448** [comment]
Should probably also update that `:lang data` accepts a `+yaml-lsp` flag under `docs/modules.org`. It should also be in the table in `:tools lsp`'s docs.

**Comment by hlissner** [comment]
Sorry for the delay. I am reconsidering moving yaml (and json) to their own modules. Possibly the others, but I haven't quite decided how. I'll post here again once I have.

**Comment by Emiller88** [comment]
Just some input both `json` and `yaml` are built-in to lsp-mode so if you have `:tools lsp`, so install the language server `yaml` works out of the box for me, with no extra flags.

**Comment by hlissner** [comment]
Sorry for the late response. As of 4a8c481 I've split the yaml and json packages into their own modules, including the changes you've proposed here. Thanks for bringing it to my attention!

**Pull request closed without merging**
