### PR TITLE
Bump to Fuco1/smartparens@be8d5c9

### PR DESCRIPTION
**Pull request by sei40kr**
# Description

Bump to Fuco1/smartparens@be8d5c9.

### CODE REVIEW

**Comment by alexandergraul** [comment]
I don't use Rust much and don't know if this is a worthy trade-off: [chars](https://doc.rust-lang.org/std/primitive.char.htm) use paired single-quotes `'a'`. Again, I don't know how often one would use chars compared to how often one uses lifetimes, just did not want this to be forgotten ;)

**Comment by sei40kr** [comment]
@alexandergraul 
Yes, this is trade-off.
Perhaps I can make it behave better since life specifiers `'` always come after `&` or in generics types.
- `struct SomeStruct<'a> {`
- `&'a i32`

**Comment by sei40kr** [comment]
@hlissner 
Thanks. I raised a PR in upstream. But we still need to update smartparens in this PR.
https://github.com/Fuco1/smartparens/pull/1003

**Comment by sei40kr** [comment]
@hlissner 
I replaced commits with the one to bump to Fuco1/smartparens@be8d5c9. Please review.

**Comment by hlissner** [comment]
Thanks for looking into this!

**Comment by bkchr** [comment]
@sei40kr does it work for you now with `<'a>`? It still autocompletes `<'a'>` for me :( And for some reason the second `>` is only added when I do this:
```
(after! rustic
  (require 'smartparens-rust))
```

**Comment by sei40kr** [comment]
@bkchr 
https://github.com/Fuco1/smartparens/blob/master/smartparens-rust.el#L62
It seems to try to handle it, but it didn't work for me.
This might be an upstream issue.

**Comment by bkchr** [comment]
Ahh I thought that this fixed it for you. If this doesn't fix it, what was the reason for this pr? ^^

**Comment by sei40kr** [comment]
@bkchr 
I tested only for `&'a mut` and this worked for me.
I should've confirmed `<'a>` too.

**Comment by bkchr** [comment]
Ahh okay, fwiw the `&` use case worked for me before as well 🤷‍♂️

**Pull request merged**
