### PR TITLE
bump: :tools magit

### LINKED ISSUE #5530: Error at startup: `forge-bug-reference-setup, (invalid-slot-name "#" :file)`
### What did you expect to happen?

Open magit

### What actually happened?

Error happens:
condition-case: Error in a Doom startup hook: find-file-hook, forge-bug-reference-setup, (invalid-slot-name "#<forge-database forge-database-15810fcacbc8>" :file)

### Describe your attempts to resolve the issue

Just disabled the forge and magit works again

### Steps to reproduce

1.  Open Emacs
2. SPC p p
3. Select Project

### Backtrace
```
Debugger entered--Lisp error: (invalid-slot-name "#<forge-database forge-database-15646ad7b398>" :file)
  signal(invalid-slot-name ("#<forge-database forge-database-15646ad7b398>" :file))
  slot-missing(#<forge-database forge-database-15646ad7b398> :file oset "/home/otavio/.emacs.d/.local/etc/forge/forge-datab...")
  #f(compiled-function (obj slots) "Set slots of OBJ with SLOTS which is a list of name/value pairs.\nCalled from the constructor routine." #<bytecode 0x15646954d2b1>)(#<forge-database forge-database-15646ad7b398> (:file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..."))
  apply(#f(compiled-function (obj slots) "Set slots of OBJ with SLOTS which is a list of name/value pairs.\nCalled from the constructor routine." #<bytecode 0x15646954d2b1>) #<forge-database forge-database-15646ad7b398> (:file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..."))
  shared-initialize(#<forge-database forge-database-15646ad7b398> (:file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..."))
  #f(compiled-function (this &optional slots) "Construct the new object THIS based on SLOTS.\nSLOTS is a tagged list where odd numbered elements are tags, and\neven numbered elements are the values to store in the tagged slot.\nIf you overload the `initialize-instance', there you will need to\ncall `shared-initialize' yourself, or you can call `call-next-method'\nto have this constructor called automatically.  If these steps are\nnot taken, then new objects of your class will not have their values\ndynamically set from SLOTS." #<bytecode 0x15646954d2dd>)(#<forge-database forge-database-15646ad7b398> (:file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..."))
  apply(#f(compiled-function (this &optional slots) "Construct the new object THIS based on SLOTS.\nSLOTS is a tagged list where odd numbered elements are tags, and\neven numbered elements are the values to store in the tagged slot.\nIf you overload the `initialize-instance', there you will need to\ncall `shared-initialize' yourself, or you can call `call-next-method'\nto have this constructor called automatically.  If these steps are\nnot taken, then new objects of your class will not have their values\ndynamically set from SLOTS." #<bytecode 0x15646954d2dd>) #<forge-database forge-database-15646ad7b398> (:file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..."))
  initialize-instance(#<forge-database forge-database-15646ad7b398> (:file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..."))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x15646954d295>)(forge-database :file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab...")
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x15646954d295>) forge-database (:file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..."))
  make-instance(forge-database :file "/home/otavio/.emacs.d/.local/etc/forge/forge-datab...")
  #f(compiled-function (class &optional variable file debug) #<bytecode 0x15646ab2fb35>)(forge-database forge--db-connection "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..." t)
  apply(#f(compiled-function (class &optional variable file debug) #<bytecode 0x15646ab2fb35>) forge-database (forge--db-connection "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..." t))
  closql-db(forge-database forge--db-connection "/home/otavio/.emacs.d/.local/etc/forge/forge-datab..." t)
  forge-db()
  forge-sql([:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))] "github.com" "grafeno-sa" "grafeno-pagamentos")
  #f(compiled-function (&rest rest) "((host owner name) &optional remote demand)\n\nReturn the repository identified by HOST, OWNER and NAME." #<bytecode 0x15646ab5b1f9>)(("github.com" "grafeno-sa" "grafeno-pagamentos") "origin" full)
  apply(#f(compiled-function (&rest rest) "((host owner name) &optional remote demand)\n\nReturn the repository identified by HOST, OWNER and NAME." #<bytecode 0x15646ab5b1f9>) ("github.com" "grafeno-sa" "grafeno-pagamentos") ("origin" full))
  #f(compiled-function (arg &rest args) #<bytecode 0x15646acdcfa5>)(("github.com" "grafeno-sa" "grafeno-pagamentos") "origin" full)
  apply(#f(compiled-function (arg &rest args) #<bytecode 0x15646acdcfa5>) (("github.com" "grafeno-sa" "grafeno-pagamentos") "origin" full))
  forge-get-repository(("github.com" "grafeno-sa" "grafeno-pagamentos") "origin" full)
  #f(compiled-function (url &optional remote demand) "Return the repository at URL." #<bytecode 0x15646ab5b18d>)("git@github.com:grafeno-sa/grafeno-pagamentos.git" "origin" full)
  apply(#f(compiled-function (url &optional remote demand) "Return the repository at URL." #<bytecode 0x15646ab5b18d>) "git@github.com:grafeno-sa/grafeno-pagamentos.git" ("origin" full))
  #f(compiled-function (arg &rest args) #<bytecode 0x15646acdcfa5>)("git@github.com:grafeno-sa/grafeno-pagamentos.git" "origin" full)
  apply(#f(compiled-function (arg &rest args) #<bytecode 0x15646acdcfa5>) ("git@github.com:grafeno-sa/grafeno-pagamentos.git" "origin" full))
  forge-get-repository("git@github.com:grafeno-sa/grafeno-pagamentos.git" "origin" full)
  #f(compiled-function (demand &optional remote) "Return the current forge repository.\n\nIf the `forge-buffer-repository' is non-nil, then return that.\nOtherwise if `forge-buffer-topic' is non-nil, then return the\nrepository for that.  Finally if both variables are nil, then\nreturn the forge repository corresponding to the current Git\nrepository, if any." #<bytecode 0x15646ab5b175>)(full)
  apply(#f(compiled-function (demand &optional remote) "Return the current forge repository.\n\nIf the `forge-buffer-repository' is non-nil, then return that.\nOtherwise if `forge-buffer-topic' is non-nil, then return the\nrepository for that.  Finally if both variables are nil, then\nreturn the forge repository corresponding to the current Git\nrepository, if any." #<bytecode 0x15646ab5b175>) full nil)
  #f(compiled-function (arg &rest args) #<bytecode 0x15646acdcfa5>)(full)
  apply(#f(compiled-function (arg &rest args) #<bytecode 0x15646acdcfa5>) full)
  forge-get-repository(full)
  forge-bug-reference-setup()
  funcall(forge-bug-reference-setup)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(forge-bug-reference-setup)
  run-hook-wrapped(doom-run-hook forge-bug-reference-setup)
  (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car (cdr e))) (symbol-name (car (cdr e))) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e)))))
  (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car ...)) (symbol-name (car ...)) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp ...) (symbol-name ...) (car ...)) (car (cdr ...)))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if ... ... ...) (car ...))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  doom-run-hooks(change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-status-mode-hook)
  apply(doom-run-hooks (change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-status-mode-hook))
  run-hooks(change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-status-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-status-mode-hook))
  run-mode-hooks(magit-status-mode-hook)
  magit-status-mode()
  magit-setup-buffer-internal(magit-status-mode nil ((magit-buffer-diff-args ("--no-ext-diff")) (magit-buffer-diff-files nil) (magit-buffer-log-args ("-n256" "--decorate")) (magit-buffer-log-files nil)))
  magit-status-setup-buffer("/home/otavio/Projetos/grafeno-pagamentos/")
  #f(compiled-function (&optional directory cache) "Show the status of the current Git repository in a buffer.\n\nIf the current directory isn't located within a Git repository,\nthen prompt for an existing repository or an arbitrary directory,\ndepending on option `magit-repository-directories', and show the\nstatus of the selected repository instead.\n\n* If that option specifies any existing repositories, then offer\n  those for completion and show the status buffer for the\n  selected one.\n\n* Otherwise read an arbitrary directory using regular file-name\n  completion.  If the selected directory is the top-level of an\n  existing working tree, then show the status buffer for that.\n\n* Otherwise offer to initialize the selected directory as a new\n  repository.  After creating the repository show its status\n  buffer.\n\nThese fallback behaviors can also be forced using one or more\nprefix arguments:\n\n* With two prefix arguments (or more precisely a numeric prefix\n  value of 16 or greater) read an arbitrary directory and act on\n  it as described above.  The same could be accomplished using\n  the command `magit-init'.\n\n* With a single prefix argument read an existing repository, or\n  if none can be found based on `magit-repository-directories',\n  then fall back to the same behavior as with two prefix\n  arguments." (interactive #f(compiled-function () #<bytecode 0x15646ae4f975>)) #<bytecode 0x156469b13bfd>)("~/Projetos/grafeno-pagamentos/")
  apply(#f(compiled-function (&optional directory cache) "Show the status of the current Git repository in a buffer.\n\nIf the current directory isn't located within a Git repository,\nthen prompt for an existing repository or an arbitrary directory,\ndepending on option `magit-repository-directories', and show the\nstatus of the selected repository instead.\n\n* If that option specifies any existing repositories, then offer\n  those for completion and show the status buffer for the\n  selected one.\n\n* Otherwise read an arbitrary directory using regular file-name\n  completion.  If the selected directory is the top-level of an\n  existing working tree, then show the status buffer for that.\n\n* Otherwise offer to initialize the selected directory as a new\n  repository.  After creating the repository show its status\n  buffer.\n\nThese fallback behaviors can also be forced using one or more\nprefix arguments:\n\n* With two prefix arguments (or more precisely a numeric prefix\n  value of 16 or greater) read an arbitrary directory and act on\n  it as described above.  The same could be accomplished using\n  the command `magit-init'.\n\n* With a single prefix argument read an existing repository, or\n  if none can be found based on `magit-repository-directories',\n  then fall back to the same behavior as with two prefix\n  arguments." (interactive #f(compiled-function () #<bytecode 0x15646ae44d49>)) #<bytecode 0x156469b13bfd>) "~/Projetos/grafeno-pagamentos/")
  magit-status("~/Projetos/grafeno-pagamentos/")
  open-projectile-with-magit("~/Projetos/grafeno-pagamentos/")
  funcall(open-projectile-with-magit "~/Projetos/grafeno-pagamentos/")
  (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))
  (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ((project-name (doom-project-name +workspaces--project-dir))) (or (+workspace-get project-name t) (+workspace-new project-name)))) (new-name (progn (or (and (memq ... cl-struct-perspective-tags) t) (signal 'wrong-type-argument (list ... persp))) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)))
  (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ((project-name ...)) (or (+workspace-get project-name t) (+workspace-new project-name)))) (new-name (progn (or (and ... t) (signal ... ...)) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil))
  (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (run-hooks ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let (...) (or ... ...))) (new-name (progn (or ... ...) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil)))
  (if (and persp-mode +workspaces--project-dir) (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ... ...) (and ... ...)))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name ...) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ... ...)) (new-name (progn ... ...))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil))))
  (let (projectile-project-root) (if (and persp-mode +workspaces--project-dir) (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal ... persp-nil-name) (+workspace-buffer-list))) (let* ((persp ...) (new-name ...)) (+workspace-switch new-name) (save-current-buffer (set-buffer ...) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil)))))
  +workspaces-switch-to-project-h()
  (closure (t) nil (+workspaces-set-project-action-fn) (+workspaces-switch-to-project-h))()
  projectile-switch-project-by-name("~/Projetos/grafeno-pagamentos/" nil)
  #f(compiled-function (project) #<bytecode 0x15646aade3d9>)("~/Projetos/grafeno-pagamentos/")
  projectile-completing-read("Switch to project: " (#("~/Projetos/grafeno-pagamentos/" 0 30 (face nil)) "~/Projetos/gem-grafeno/" "~/Projetos/fonte-nova/" "~/Projetos/ecovida_opac/" "~/Projetos/cep-api/" "~/Projetos/cadastros/" "~/Projetos/boletador-2/" "~/.doom.d/" "~/.emacs.d/") :action #f(compiled-function (project) #<bytecode 0x15646aade3d9>))
  projectile-switch-project(nil)
  #<subr funcall-interactively>(projectile-switch-project nil)
  apply(#<subr funcall-interactively> (projectile-switch-project nil))
  funcall-interactively(projectile-switch-project nil)
  #<subr call-interactively>(projectile-switch-project nil nil)
  apply(#<subr call-interactively> (projectile-switch-project nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> projectile-switch-project nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (projectile-switch-project nil nil))
  call-interactively(projectile-switch-project nil nil)
  command-execute(projectile-switch-project)
```

### System Information

https://pastebin.com/wG1VivnN

### PR DESCRIPTION
**Pull request by catap**
magit/magit@1e40d00 -> magit/magit@f53148a
magit/forge@f97bc47 -> magit/forge@483baae

Fix magit/forge#382
Fix #5530

### CODE REVIEW

**Comment by iyefrat** [comment]
Can you update the bump? There has been another bugfix since you opened the PR. Thanks!

**Comment by catap** [comment]
@iyefrat sure

**Comment by iyefrat** [comment]
@catap Thanks! however, the commit message body is now out of date with the bump, can you fix that as well? Also, the footer doesn't fit doom emacs' [commit conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854), can you change it to `Fix magit/forge#382`?

**Comment by catap** [comment]
@iyefrat maybe you know a way to generate such messages?

**Comment by iyefrat** [comment]
Oh wait, never mind, you did this correctly, github just truncates the links without providing a way to see the full commit message. The commit linting ci did pass after all :).

**Comment by catap** [comment]
@iyefrat thanks for magic command, I'll use them next time.

**Review by hlissner — CHANGES_REQUESTED** [review]
I think this is ready to merge, but (and sorry for the nitpick) could you reword the commit messages so that:

1. ~~the commit hashes are 12 characters long, rather than 7? It's a [git convention](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854) I've begun to enforce only recently.~~ Nevermind, hadn't realized Github truncates references even on the commit page.

2. Could you append a `Fix #5530` line to the footer, as this fixes that issue too.

**Comment by hlissner** [comment]
Briefly forgot I could squash it myself. Anyhow, thanks again for your help!

**Pull request merged**
