### PR TITLE
Bump :ui doom

### PR DESCRIPTION
**Pull request by maikol-solis**
hlissner/emacs-doom-themes@7307dc6 -> hlissner/emacs-doom-themes@294a432

### CODE REVIEW

**Comment by maikol-solis** [comment]
Thanks @hlissner  I made the change.

**Comment by hlissner** [comment]
I meant in the commit message, not the title of the PR.

**Comment by maikol-solis** [comment]
Sorry @hlissner I don't know how to change the commit title. I can erase it and do it again.

**Comment by hlissner** [comment]
That's fine. I've bumped the module in cd3c865. Thanks for bringing it to my attention!

**Comment by maikol-solis** [comment]
You're welcome. I'll try to be more careful in the future.

**Pull request closed without merging**
