### PR TITLE
Rebind "\"" to cider-jack-in-cljs

### PR DESCRIPTION
**Pull request by levitanong**
cider-jack-in-clojurescript is deprecated, and cider advises to use `cider-jack-in-cljs` instead.

### CODE REVIEW

**Comment by hlissner** [comment]
Looks good to me! If you'll kindly retarget this PR at the `straight` branch, I'll be happy to merge it.

**Comment by levitanong** [comment]
@hlissner retargeted!

**Comment by hlissner** [comment]
Would you might rebasing it onto straight? A little merge history was pulled into this PR.

**Comment by levitanong** [comment]
Closing in favor of #1612

**Pull request closed without merging**
