### PR TITLE
Enable native ligature support on emacs-28/mac

### PR DESCRIPTION
**Pull request by dlesl**
This works for me using emacs HEAD (`emacsGit` from the [Nix emacs overlay](https://github.com/nix-community/emacs-overlay)) with Fira Code and Iosevka.

### CODE REVIEW

**Comment by gagbo** [comment]
You don't have "HARFBUZZ" in your `system-configuration-features` variable ? Can you paste the output of `M-x doom/info` please ?

**Comment by gagbo** [comment]
Looks like you should have harfbuzz in the features from my very light understanding of Nix eco system https://github.com/nix-community/emacs-overlay/blob/b839a0ed8bdcceec92bc4a6a93211503501f7dd4/default.nix#L49

**Comment by dlesl** [comment]
`system-configuration-features`: `JPEG TIFF PNG RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER`.

AFAIK on mac emacs uses native text rendering (but I am not sure). However I guess it's possible that someone might be running emacs under X11 on mac, in which case harfbuzz would be needed -- maybe this is worth checking for?

**Comment by dlesl** [comment]
I've updated the PR to check for `(featurep 'ns)` or harfbuzz, I think this should cover the X11-on-mac case.

**Comment by hlissner** [comment]
Makes sense to me. Thanks!

**Pull request merged**
