### PR TITLE
docs(biblio): improve grammar

### PR DESCRIPTION
**Pull request by edgar-vincent**
A few minor grammar-related changes to the biblio module's README.

### CODE REVIEW

**Review by hlissner — CHANGES_REQUESTED** [review]
Please reword the commit to conform to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854) (i.e. `nit` is not the correct type for these kinds of commits):

```
docs(biblio): improve grammar
```

**Comment by edgar-vincent** [comment]
Done. I am sorry about that. I did read the git conventions, but as the scope for the `docs` type is described as `The basename of the target org file in docs/*`, I thought that `docs` didn't apply to module documentation, only to files in `docs/`.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks!

> I thought that docs didn't apply to module documentation, only to files in docs/.

I see how that might be confusing. I've reworded to to avoid this in the future.

**Comment by edgar-vincent** [comment]
Thank you @hlissner!

**Pull request merged**
