### PR TITLE
Add treemacs module

### PR DESCRIPTION
**Pull request by ar1a**
Seems pretty handy

### CODE REVIEW

**Comment by hlissner** [comment]
Thanks for this!

**Comment by hlissner** [comment]
Oh, forgot to mention: I removed the `:leader` keybinds because they belong in `:config default`, _however_ I haven't set any default keys for treemacs. I need to decide what they should be, but will do that after the big keybind refactor planned for 2.1.1.

**Comment by ar1a** [comment]
Great, I'll make an issue so we don't forget.

**Comment by hlissner** [comment]
Side note: treemacs still creates `~/.emacs.d/.cache`, which I've filed a PR to fix (Alexander-Miller/treemacs#212).

**Pull request merged**
