### PR TITLE
fix(org): parity for headlines & items in `+org--insert-item`

### PR DESCRIPTION
**Pull request by vherrmann**
When you have a structure like
``` org
- ThisX
  - Hi 
  - No
```
in org mode and execute `+org-insert-item` (the "X" represents the pointer), with the current behavior the following is created:
``` org
- This
  - X
  - Hi 
  - No
```

This pr will change the behavior, so that its equivalent to the one of headlines:
``` org
- This
  - Hi 
  - No
- X
```

### CODE REVIEW

**Comment by nipuna-perera** [comment]
I think the way this works now is better. It is possible to achieve what you are looking for by using `C-RET` instead. Eg:

```
- ThisX
   - Hi
   - No
```

`C-RET` will result in

```
- This
   - Hi
   - No
- X
```
For simple `RET` I would expect the current behavior of creating a new sub-item

**Comment by vherrmann** [comment]
@nipuna-perera As far as i know, C-RET is bound to `+org/insert-item-below`, which uses `+org/insert-item`, while `RET` changes nothing.

**Comment by nipuna-perera** [comment]
> @nipuna-perera As far as i know, C-RET is bound to `+org/insert-item-below`, which uses `+org/insert-item`, while `RET` changes nothing.

You are right, my bad. I forgot I had mine set up according to this - https://kitchingroup.cheme.cmu.edu/blog/2017/04/09/A-better-return-in-org-mode/

**Review by hlissner — APPROVED** [review]

**Review by hlissner — CHANGES_REQUESTED** [review]
`develop` is EOL. Could you target the `master` branch instead?

**Comment by vherrmann** [comment]
Of course

**Review by hlissner — APPROVED** [review]

**Review by hlissner — CHANGES_REQUESTED** [review]
Could you rebase it onto the top of `master`?

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
LGTM. Thanks for your help (and putting up with my nits)!

**Pull request merged**
