### PR TITLE
nit: fix several docstring typos and minor code tweak

### PR DESCRIPTION
**Pull request by lelit**
Little defects I noticed while browsing the sources and documentation.

### CODE REVIEW

**Comment by jeetelongname** [comment]
One note, the docs are being rewritten on the `rewrite-docs` branch, I would send your README corrections to that branch (if they exist that is)

**Review by hlissner — CHANGES_REQUESTED** [review]
Please revert the changes to :editor format's README.org and `docs/getting_started.org` files. (See our [do-not-PR](https://gist.github.com/hlissner/bb6365626d825aeaf5e857b1c03c9837) list, which should've been mentioned in the pull request template)

**Comment by lelit** [comment]
> Please revert the changes to :editor format's README.org and `docs/getting_started.org` files. (See our [do-not-PR](https://gist.github.com/hlissner/bb6365626d825aeaf5e857b1c03c9837) list, which should've been mentioned in the pull request template)

My bad, sorry. Doing that now.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
No worries! Thanks for your help!

**Pull request merged**
