### PR TITLE
Fix eglot integration with flycheck

### PR DESCRIPTION
**Pull request by gagbo**
EDIT : use `eglot-flymake-backend` new version properly.

### CODE REVIEW

**Comment by gagbo** [comment]
Fixes #4828

**Review by hlissner — CHANGES_REQUESTED** [review]
Could you rebase the `package!` bump into a separate bump commit?

```
Bump eglot

joaotavora/eglot@2fbcab2 -> joaotavora/eglot@f930a09
```

**Comment by gagbo** [comment]
Do you want 2 commits here, or 2 PRs ?

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
That's how I wanted it! Thanks again for your help!

**Pull request merged**
