### PR TITLE
ivy-rich: add all-the-icon if it exists

### PR DESCRIPTION
**Pull request by seanfarley**
Most of this diff is just re-indentation, only the first few lines are new.

### CODE REVIEW

**Comment by seanfarley** [comment]
Gratuitous screenshots: (ivy-posframe vs regular)

screen shot 2019-02-07 at 10 47 32 pm
screen shot 2019-02-07 at 10 49 02 pm

**Comment by rschmukler** [comment]
Mild duplicate of #1050 - which makes this configurable via variable instead (as it used to be). I have no preference of which implementation gets used - just linking the issue for posterity.

**Comment by seanfarley** [comment]
Ah, I missed your PR @rschmukler! Sorry about that. Yours looks much better than mine!

**Comment by seanfarley** [comment]
Hmm, I couldn't get yours to work, @rschmukler. I suspect something has changed in the way the columns are calculated?

**Comment by rschmukler** [comment]
@seanfarley sorry on the delay. I just confirmed that it's still working for me. Did you enable it via the variable? You will need the below somewhere in your `init.el`

```
(setq +ivy-buffer-icons t)
```

**Comment by seanfarley** [comment]
Ah, I had that set in the wrong place `(ivy +ivy-buffer-icons)`. I'll try this out and report back.

**Comment by rschmukler** [comment]
@seanfarley actually looking at your specific  screenshots, this PR modifies the `ivy-switch-buffer` command, while mine modifies `counsel-projectile-switch-project` and `counsel-projectile-find-file`. Sorry for not noticing this sooner.

I can add functionality to my branch to add the icons to the buffer switcher as well.

**Comment by rschmukler** [comment]
@seanfarley just pushed a new version of my branch with the icons applying to the `ivy-switch-buffer` command. Should be good now!

**Comment by seanfarley** [comment]
Oooo, very nice. I really like yours! I'll go ahead and close mine!

P.S. it seems you rebased too many commits (you have ~73 commits in your PR now but it should be just one)

**Comment by rschmukler** [comment]
@seanfarley thanks for the heads up - I'll see what happened over there.

**Pull request closed without merging**
