### PR TITLE
More convenient search buffer

### PR DESCRIPTION
**Pull request by nhamlh**

### CODE REVIEW

**Comment by hlissner** [comment]
Makes sense to me. Thanks!

**Comment by facelesspanda** [comment]
awww, now I have to *select* what I want to search? How is this convenient? Guess I have to add it back in my own config then...

**Comment by hlissner** [comment]
@facelesspanda My bad. I've added back `SPC s S` in 76eae7b

**Comment by facelesspanda** [comment]
> @facelesspanda My bad. I've added back `SPC s S` in 76eae7b

That's great news! Thanks 😄

**Pull request merged**
