### PR TITLE
[emacs lisp] Add bindings for debugging defuns

### PR DESCRIPTION
**Pull request by rgrinberg**
`, d f` - turn on debugging for defun
`, d F` - turn off debugging for defun

### CODE REVIEW

**Comment by rgrinberg** [comment]
Would be nice to add some highlighting to debugged functions but I'm not sure how to do that.

**Comment by rgrinberg** [comment]
Good call. I fixed the naming convention.

**Comment by rgrinberg** [comment]
@hlissner How about just merging the functions without adding the keybindings? Those are already quite useful on their own since one does not have convenient functions for them.

I agree the keybindings could use a bit more work especially since it makes sense to create binding scheme that will be consistent between `debug` and `edebug`.

**Comment by rgrinberg** [comment]
@hlissner ping?

**Comment by hlissner** [comment]
Sorry for the delay and thanks for the help!

**Pull request merged**
