### PR TITLE
Remove space from mc prefix map

### PR DESCRIPTION
**Pull request by DidacGit**
Change the space of the multiple-cursors keymap to a "-".

### CODE REVIEW

**Comment by hlissner** [comment]
Hi! Thanks for the PR, but I cannot accept it. This is not an error. The label is general and not specific to the "multiple-cursors" package, and could one day be replaced, where a better implementation to appear.

**Comment by DidacGit** [comment]
I'm sorry but I don't understand. This is the reason why Doom's multiple cursors map is called "doom-leader-multiple cursors-map" (with a space), isn't it? Why can't it be changed?

**Comment by hlissner** [comment]
Ah, my bad! I misunderstood the PR. I've merged it now. Sorry for the trouble and thanks for the help!

**Comment by DidacGit** [comment]
No problem! Thank you as always for your amazing work!

**Pull request merged**
