### PR TITLE
Update list of lang/python considered conda homes

### PR DESCRIPTION
**Pull request by nelson-liu**
For several years, the default location for a miniconda install has been `~/miniconda3` (`~/miniconda2` if using the python 2 version). This PR adds this path to the list considered by the conda package.

### CODE REVIEW

**Comment by hlissner** [comment]
Looks good to me. Would you mind retargeting this PR to the `straight` branch? We're prepping to merge it, and it'd be a big help if PRs were made there for the time being.

**Comment by yuhan0** [comment]
The Homebrew cask install path for miniconda was recently changed to `/usr/local/Caskroom/miniconda/base`, should be a good idea to add that as well - https://github.com/Homebrew/homebrew-cask/pull/66544

**Comment by nelson-liu** [comment]
thanks for the info @yuhan0 , I've added the path. @hlissner , I've retargeted to pr against `straight`.

**Comment by hlissner** [comment]
Good work. Thanks for the help!

**Pull request merged**
