### PR TITLE
Adds js pretty symbols for `rjsx-mode`

### PR DESCRIPTION
**Pull request by qleguennec**

### CODE REVIEW

**Comment by hlissner** [comment]
Good idea. Thanks for the PR!

**Comment by qleguennec** [comment]
@hlissner I tried what you did in 10b22b9 but i couldn't make it work. As of 10b22b9, unicode characters aren't displayed in `rjsx-mode`.

**Comment by hlissner** [comment]
Have you changed `+pretty-code-enabled-mode`? The default is `t` (enabled in all modes).

**Comment by qleguennec** [comment]
@hlissner I haven't.

**Comment by qleguennec** [comment]
@hlissner Any news on this? Can you reproduce the bug?

**Pull request merged**
