### PR TITLE
Brain (WiP)

### PR DESCRIPTION
**Pull request by patrl**
Add wiki-like functionality to org-mode via `org-brain`, behind the org module flag `+brain`.

 - TODO prevent brain from loading every org-file in `org-brain-path` whenever, e.g., I want to add a parent or child.

N.b. the keybindings are based on @AloisJanicek 's [doom config](https://github.com/AloisJanicek/.doom.d/blob/master/%2Bbindings.el).

### CODE REVIEW

**Comment by hlissner** [comment]
I'm interested to learn more about org-brain and see where this PR goes. I'll leave this org-brain tutorial here for personal reference:

https://www.youtube.com/watch?v=3EGOwfWok5s

**Comment by ocharles** [comment]
@patrl what's the status of this? Would love to use `org-brain` more!

**Comment by hlissner** [comment]
Sorry for a _tremendously_ late reply. I'm still interested in org-brain, but this PR's commit history has gone a bit off course and the lang/org module has diverged dramatically since this PR was opened. If you're willing to make a `lang/org/contrib/brain.el` and add a `+brain` flag, I'll happily accept it, but for the time being I'll close this PR.

Thanks for bringing it to my attention!

**Comment by patrl** [comment]
No worries, I stopped using brain a while ago. Thanks for closing the PR, it completely slipped my mind.

**Pull request closed without merging**
