### PR TITLE
show all available lsp servers when switching

### PR DESCRIPTION
**Pull request by chaoky**
when invoking `+lsp/switch-client` show all available lsp servers instead of only high priority ones

### CODE REVIEW

**Comment by chaoky** [comment]
somewhat related, maybe should report as a bug:
`+lsp/switch-client` sometimes restores the client priority before `lsp-workspace-restart` is finished, making so the server switch doesn't happen, putting the priority restauration on a 1s timer solved the issue for me, but doesn't seem like a good solution

**Comment by hlissner** [comment]
Perhaps resetting the priority in `lsp-after-initialize-hook` would work? Assuming that hook fires when the new workspace is initialized.

**Comment by chaoky** [comment]
`lsp-after-initialize-hook` works :)

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks!

**Pull request merged**
