### PR TITLE
Align org-roam emacs-bindings with evil-bindings 

### PR DESCRIPTION
**Pull request by brianmcgillion**

### CODE REVIEW

**Comment by brianmcgillion** [comment]
@hlissner I just noticed that these key bindings are listed directly in default/+evil-bindings, so should I move the emacs one to +emacs-bindings also?

**Comment by hlissner** [comment]
> should I move the emacs one to +emacs-bindings also?

Sounds like a good idea!

**Comment by brianmcgillion** [comment]
Sorry, I misunderstood completely! will do!

**Comment by hlissner** [comment]
No worries! Thanks for the quick response and the PR!

**Pull request merged**
